### ISSUE TITLE
Key Error (revisted!)

### ISSUE THREAD

**Issue by altanner** [chbrown/liwc-python#6] opened 2019-07-11 15:29 UTC
Hello,
Thanks for providing these scripts. I know you've closed this issue before but I am also getting a key error. I get why it is erroring, in that it doesn't like lines with unusual structure and symbols I guess. But does it normally deal with them fine? Here is the traceback:

```sh
at9362$ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    parse, category_names = liwc.load_token_parser('LIWC2007_English100131.dic')
  File "python/liwc/__init__.py", line 76, in load_token_parser
    lexicon, category_names = read_dic(filepath)
  File "python/liwc/__init__.py", line 27, in read_dic
    lexicon[parts[0]] = [category_mapping[category_id] for category_id in parts[1:]]
  File "python/liwc/__init__.py", line 27, in <listcomp>
    lexicon[parts[0]] = [category_mapping[category_id] for category_id in parts[1:]]
KeyError: '<of>131/125'
```

Grateful for any help :)

**Comment by altanner** [comment] 2019-07-11 15:46
Taking out two lines (one with "<" in it, one with "(" in it) solves the issue - but I am still interested in how this is working for others without deleting those two lines from the dictionary.

`sed -i -e '/[<(]/d' LIWC2007_English100131.dic`
fixes things for me.

**Comment by mengyingzhou** [comment] 2019-12-16 06:25
btw, how to fix a similar bug when I load the 2015 dictionary?

thx

**Comment by chbrown** [comment] 2019-12-16 14:13
Hi! I believe this is a duplicate of #3 at this point (not that #3 is solved, but for consolidation). 

Please open a new issue (albeit yet another 😉) if you encounter any problems aside from the two caveats in https://github.com/chbrown/liwc-python/issues/3#issuecomment-566074276

**Closed by chbrown** 2019-12-16 14:13 UTC

**Comment by StevenLi-DS** [comment] 2020-02-06 02:56
@altanner @chbrown I may have to keep those two lines especially for

`like	(02 134)125/464	(02 134)126	(02 134)126	253`

@altanner It seems like you have found a solution for that? Could you please be more specific? How should I include your solution in my code or modify the `.dic` file?
